controller_list:
  - name: rarm_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - r_arm_usy
      - r_arm_shx
      - r_arm_ely
      - r_arm_elx
      - r_arm_uwy
      - r_arm_mwx
  - name: larm_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - l_arm_usy
      - l_arm_shx
      - l_arm_ely
      - l_arm_elx
      - l_arm_uwy
      - l_arm_mwx
  - name: rleg_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - r_leg_kny
      - r_leg_lax
      - r_leg_lhy
      - r_leg_mhx
      - r_leg_uay
      - r_leg_uhz
  - name: lleg_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - l_leg_kny
      - l_leg_lax
      - l_leg_lhy
      - l_leg_mhx
      - l_leg_uay
      - l_leg_uhz
  - name: torso_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - back_lbz
      - back_mby
      - back_ubx
